### PR TITLE
Initial gradle build system for randori compiler. Added also gradle wrap...

### PR DESCRIPTION
**Pull request by martinopic**
Simple gradle build system, it resolves correctly all dependencies in maven repositories, I've removed all jars from lib but had to add compiler.jar.

```
gradle tasks (get a list of all available tasks)
gradle jar (build jar)
gradle install (create source, javadoc and jar archives and publish to local maven repository)
gradle idea (configure for Idea IDE)
gradle javadoc
gradle clean
```

I think next step should be publish to maven central repo through sonatype, someone authoritative for the project should do the process though (https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide)

I adapted gradle to current directory struture but it might also be a good idea to adapt the directory to gradle/maven standard.

### CODE REVIEW

**Comment by rolandzwaga** [comment]
@martinopic  Hi Martino, the current branch that we're developing the compiler in is actually 'compiler-api', so I'm afraid you've developed against potentially old code.
Sorry for the mixup... Can you check and re-send your pull request for the correct branch?

**Comment by martinopic** [comment]
@rolandzwaga  done (see new pull request)

**Comment by teotigraphix** [comment]
@martinopic What is the directory structure, all I have used is ant builds.

**Comment by martinopic** [comment]
Both maven and gradle use a "standard" directory structure for source code and other resources (e.g. java code in "src/main/java" instead of just "src"), this allows to write less code in the build system (convention over configuration) and it feels "standard" to people used to these build system. Just a minor issue (if an issue at all...)

**Comment by teotigraphix** [comment]
@martinopic I am new at gradle but I think there is something wrong with the eclipse task,.

I have done a cleanEclipse and eclipse after install. I am getting build errors about my source path files not being able to find files in the same source path. I am guessing you did not test this in Eclipse? Errors are like;

```
The method addCategory(IBundleCategoryType) of type BundleContainer must override a superclass method   BundleContainer.
```

Thought I had it until the last step, I can't do any work until I get this figured out.

**Comment by martinopic** [comment]
Sorry no test with eclipse I thought you were all using IntelliJIDEA (the plugin...) as me...

**Comment by teotigraphix** [comment]
Nope, I am an Eclipse guy. I cannot for some reason write Java in IntelliJ. :)

**Comment by martinopic** [comment]
So I guess the fix is buying IntellijIDEA ;-) 

BTW build system IDE plugins usually lags behind IDE features and/or give problems, I'll try to test with eclipse asap.

**Comment by teotigraphix** [comment]
I have IntelliJ Ultimate. I don't want to use it for Java. :) Meaning, I use it for AS3 and Randori plugin dev. But I don't write my compiler code in it.

**Pull request closed without merging**
